"""Generate `.env.example`, and re-order `.env` to match it.

Both files are derived from `rag.config.Settings` rather than maintained by
hand, because hand-maintained pairs drift: a setting gets added to one, the
other is forgotten, and the next person to set the project up discovers it by
hitting a default they did not know existed. Here the field list, the order and
the grouping all come from the class itself, so a new setting appears in both
files the moment it exists.

    python scripts/gen_env.py            # rewrite .env.example, re-order .env
    python scripts/gen_env.py --check    # verify both are current, change nothing

`--check` is what the test uses.

Only `.env.example` gets generated values. `.env` keeps whatever is already in
it -- it holds real credentials, and regenerating it would either wipe them or
print them into a template. Its keys are re-ordered to match, and any setting
missing from it is appended with its default so the two files stay comparable
line by line.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from rag.config import Settings  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]

HEADER = """\
# Configuration for the Northwind Knowledge Assistant.
#
# Every setting the system reads is listed here, in the order it is declared in
# `src/rag/config.py` -- which is the only module that reads the environment.
# Generated by `python scripts/gen_env.py`; edit the Settings class, not this
# file.
#
# Values marked REQUIRED have no default: the app will not start without them.
"""

# Section headings, keyed on the field that opens the section.
SECTIONS = {
    "doc_source": "Document source",
    "live_rescan_seconds": "Live monitoring",
    "azure_storage_account": "Azure Blob Storage (used when DOC_SOURCE=blob)",
    "doc_parser": "Parsing",
    "azure_openai_endpoint": "Azure OpenAI — embeddings and chat",
    "azure_openai_batch_endpoint": "Azure OpenAI — batch (bulk extraction backfill)",
    "azure_search_endpoint": "Azure AI Search",
    "cocoindex_db": "CocoIndex incremental state",
    "neo4j_uri": "Neo4j knowledge graph",
    "graph_extraction_enabled": "Relationship extraction",
    "retrieval_top_k": "Retrieval",
    "api_default_departments": "API",
    "cost_per_1m_input": "Cost accounting (USD per 1M tokens, for reporting only)",
    "chunk_target_tokens": "Chunking",
}

# One line per setting. Says what it is, and why it matters where that is not
# obvious from the name.
DOCS: dict[str, str] = {
    "doc_source": "Where documents come from: 'local' (LOCAL_SOURCE_DIR) or 'blob'.",
    "local_source_dir": "Root folder scanned when DOC_SOURCE=local, one subfolder per department. Defaults to the bundled source_data/; point it at your own documents.",
    "departments": "The department list; must match the folder names under LOCAL_SOURCE_DIR (case-insensitive). Drives what is monitored, ingested, labelled and retrievable. Adding one is an env edit plus a folder.",
    "included_patterns": "Glob patterns a file must match to be ingested.",
    "department_sources": "Optional {\"HR\": \"people-ops\"} map, when a department's folder is not named after it. Absent departments use their own name.",
    "unknown_department_policy": "What to do with a document whose folder matches no department: 'skip' or 'ingest'.",
    "live_rescan_seconds": "Full rescan interval in --live mode; a safety net for filesystem events the OS watcher drops.",
    "blob_poll_seconds": "How often the Blob source re-lists ETags to detect changes.",
    "azure_storage_account": "Storage account name.",
    "azure_storage_container": "Container holding the documents.",
    "azure_storage_key": "Account key. Either this pair or the connection string below.",
    "azure_storage_connection_string": "Full connection string; account and key are derived from it if those are blank.",
    "azure_blob_prefix": "Only ingest blobs under this prefix. Blank = the whole container.",
    "doc_parser": "'auto' routes per format and per document (local parsers, OCR for scanned PDFs). 'local' never calls Document Intelligence; 'azure' always does.",
    "azure_docint_endpoint": "Document Intelligence endpoint. Needed for scanned PDFs and images.",
    "azure_docint_key": "Document Intelligence key.",
    "scanned_pdf_char_threshold": "Below this many extractable characters per page a PDF is treated as scanned and sent to OCR. Corpus PDFs read 1,300-1,900; a scanned page reads 0.",
    "vision_captions_enabled": "Caption embedded figures with a vision call, making charts retrievable. Off by default: one call per image.",
    "azure_openai_endpoint": "REQUIRED. Azure OpenAI endpoint for embeddings and chat.",
    "azure_openai_key": "REQUIRED. Azure OpenAI key.",
    "azure_openai_api_version": "API version for embeddings.",
    "azure_openai_embedding_deployment": "REQUIRED. Embedding deployment name (not the model id).",
    "embedding_dimensions": "Must match the embedding model and the search index's vector field.",
    "embedding_batch_size": "Texts per embedding request.",
    "azure_openai_chat_deployment": "Chat deployment name. Used for planning, answering, verification and extraction.",
    "azure_openai_chat_api_version": "Tracked separately from the embedding version: strict JSON-schema structured outputs need a newer preview track.",
    "azure_openai_batch_endpoint": "Blank = reuse the values above. Batch needs a 'globalbatch' or 'datazonebatch' deployment, which usually means a separate resource, since one account holds a single SKU per model.",
    "azure_openai_batch_key": "Key for the batch resource.",
    "azure_openai_batch_deployment": "Batch deployment name.",
    "azure_openai_batch_api_version": "API version for the batch resource.",
    "azure_search_endpoint": "REQUIRED. Azure AI Search endpoint.",
    "azure_search_key": "REQUIRED. Admin key; the pipeline creates and writes the index.",
    "azure_search_index": "REQUIRED. Index name. Recreated if its field schema does not match.",
    "azure_search_semantic_config": "Semantic configuration name used for cross-encoder reranking.",
    "cocoindex_db": "Filesystem path to CocoIndex's embedded LMDB state (what was processed, at what fingerprint).",
    "neo4j_uri": "Bolt URI. Use bolt+s:// for TLS.",
    "neo4j_user": "Neo4j username.",
    "neo4j_password": "Neo4j password.",
    "neo4j_database": "Database name.",
    "graph_enabled": "Write the graph at all. Off = vector-only; retrieval degrades rather than failing.",
    "graph_extraction_enabled": "Extract entities and typed relations with an LLM. Off leaves only the deterministic Document/Section/Chunk structure.",
    "graph_extract_mode": "'online' extracts during ingest (right for incremental changes); 'batch' uses the Azure OpenAI Batch API at half price for a bulk backfill.",
    "graph_extract_min_tokens": "Units shorter than this are skipped. Measured: at 40 this dropped a real 38-token account-lockout rule.",
    "graph_extract_min_signal": "Minimum density of entity-bearing content (money, dates, durations, obligations) before a unit is worth an LLM call.",
    "graph_extract_pack_tokens": "Small units are packed into one call up to this budget, amortising the fixed prompt overhead.",
    "graph_extract_concurrency": "Concurrent extraction calls, with backoff on 429.",
    "extraction_cache_path": "Content-hash memo store. Re-ingesting unchanged text costs nothing.",
    "document_registry_path": "One row per document, holding what cross-document supersession resolution needs.",
    "boilerplate_doc_threshold": "Identical text appearing in at least this many documents is boilerplate: extracted once, not once per document.",
    "entity_merge_threshold": "Similarity above which two entity mentions are treated as the same entity.",
    "retrieval_top_k": "Chunks passed to the answer prompt for a single-part question. Grows with the number of sub-queries.",
    "vector_k": "Candidates the vector side feeds into fusion. 50 because Azure's semantic ranker reranks the top 50 -- fewer and it has nothing to work with.",
    "rerank_top_k": "Candidates fetched per query before fusion, and the ceiling on the context budget.",
    "sufficiency_threshold": "On the reranker's 0-4 scale. Below this the system abstains instead of answering.",
    "query_cache_enabled": "Cache answers. Partitioned by department scope; refusals are never cached.",
    "semantic_cache_threshold": "Cosine similarity for a semantic cache hit. Deliberately tight -- a loose threshold is how caches leak one scope's answer to another.",
    "api_default_departments": "Departments granted when the auth gateway supplies no scope. EMPTY IS THE SECURE DEFAULT: a request that establishes no identity reads nothing. Set only for a single-tenant demo.",
    "query_cache_ttl_seconds": "Cache entry lifetime. A cache with no TTL is a slow-motion correctness bug: policies change.",
    "query_cache_max_entries": "Per-scope cache size before the oldest entries are evicted.",
    "cost_per_1m_input": "Input token price, for the cost report only. Update if the model or tier changes.",
    "cost_per_1m_cached_input": "Price for prompt-cache hits, billed lower than fresh input.",
    "cost_per_1m_output": "Output token price. Note output is ~96% of the extraction bill.",
    "cost_per_1m_embedding": "Embedding token price.",
    "chunk_target_tokens": "Target prose chunk size before splitting.",
    "chunk_max_tokens": "Hard ceiling on a prose chunk.",
    "chunk_overlap_tokens": "Overlap between consecutive prose chunks, so a split does not orphan a sentence.",
    "tokenizer_encoding": "tiktoken encoding used for every token count in the pipeline.",
}


def _default_for(name: str, field) -> str:
    """The value `.env.example` should show for a field."""
    if field.is_required():
        return ""
    default = field.default_factory() if field.default_factory else field.default
    if default is None:
        return ""
    if isinstance(default, bool):
        return "true" if default else "false"
    if isinstance(default, (list, dict)):
        import json

        return json.dumps(default, separators=(",", ":"))
    return str(default)


def render_example() -> str:
    lines = [HEADER]
    for name, field in Settings.model_fields.items():
        if name in SECTIONS:
            lines.append(f"\n# ---------------------------------------------------------------------\n"
                         f"# {SECTIONS[name]}\n"
                         f"# ---------------------------------------------------------------------")
        doc = DOCS.get(name)
        if doc is None:  # pragma: no cover - guarded by the test
            raise SystemExit(
                f"scripts/gen_env.py: no description for setting {name!r}. "
                "Add one to DOCS so the template explains every field."
            )
        lines.append(f"# {doc}")
        lines.append(f"{name.upper()}={_default_for(name, field)}")
    return "\n".join(lines).rstrip() + "\n"


def _existing_values(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and "=" in stripped:
            key, value = stripped.split("=", 1)
            values[key.strip()] = value
    return values


def render_env(existing: dict[str, str]) -> str:
    """`.env` in the same order, grouping and comments as the template.

    The comments are repeated here rather than left only in `.env.example`
    because this is the file people actually edit -- being told what
    `SUFFICIENCY_THRESHOLD` means at the moment you are changing it is worth
    more than a duplicate line in a generated file.
    """
    lines = [
        "# Local configuration.",
        "#",
        "# Same fields, order and comments as .env.example -- both are generated",
        "# from `rag.config.Settings` by `python scripts/gen_env.py`, which keeps",
        "# the values already set here. Real credentials live in this file and it",
        "# is gitignored; never commit it.",
    ]
    for name, field in Settings.model_fields.items():
        if name in SECTIONS:
            lines.append(f"\n# ---------------------------------------------------------------------\n"
                         f"# {SECTIONS[name]}\n"
                         f"# ---------------------------------------------------------------------")
        key = name.upper()
        lines.append(f"# {DOCS[name]}")
        lines.append(f"{key}={existing.get(key, _default_for(name, field))}")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Verify both files are current; write nothing.")
    args = parser.parse_args()

    example_path, env_path = ROOT / ".env.example", ROOT / ".env"
    example = render_example()
    env = render_env(_existing_values(env_path))

    if args.check:
        stale = []
        if not example_path.exists() or example_path.read_text() != example:
            stale.append(".env.example")
        if env_path.exists() and env_path.read_text() != env:
            stale.append(".env")
        if stale:
            print(f"stale: {', '.join(stale)} -- run `python scripts/gen_env.py`")
            return 1
        print("env files are current")
        return 0

    example_path.write_text(example)
    print(f"wrote {example_path.relative_to(ROOT)}")
    if env_path.exists():
        env_path.write_text(env)
        print(f"re-ordered {env_path.relative_to(ROOT)} (values preserved)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
